import Head from "next/head";
import { useEffect, useState } from "react";
import {
  Card,
  Fab,
  Dialog,
  Select,
  Snackbar,
  IconButton,
  DialogActions,
  DialogContent,
  TextField,
  Button,
  DialogContentText,
  DialogTitle,
} from "@material-ui/core";
import axios from "axios";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { ProjectDataBase } from "../interfaces/props";
import { AddRounded, Close } from "@material-ui/icons";

export default function Home() {
  const router = useRouter();
  const [open, setOpen] = useState<boolean>(false);
  const [snackOpen, setSnackOpen] = useState<boolean>(false);
  const [name, setName] = useState<string>("");
  const [desc, setDesc] = useState<string>("");
  const [type, setType] = useState<string>("project");
  const [databases, setDataBases] = useState<ProjectDataBase[]>([]);
  const [isLoading, setLoading] = useState<boolean>(true);

  const handleClickOpen = () => {
    setOpen(true);
  };

  const handleTypeChange = (e: any) => {
    setType(e.target.value);
  };

  const handleClose = () => {
    setOpen(false);
  };

  const getData = async () => {
    const res = await axios.get("https://fast-savannah-26464.herokuapp.com/");
    setDataBases(res.data);
    setLoading(false);
  };

  useEffect(() => {
    getData();
  }, []);


  const AddProject = async () => {
    setOpen(false);
    const data = {
      name: name,
      type: type,
      desc: desc,
    };
    const res = await axios.post(
      `https://fast-savannah-26464.herokuapp.com/${type}`,
      data
    );
    if (res.status == 200) {
      setSnackOpen(true);
      getData();
    }
  };

  const NavigatePages = (
    dbDesc: string,
    dbType: string,
    dbName: string,
    dbId: string
  ) => {
    let currentDb = {
      dbname: dbName,
      dbdesc: dbDesc,
      dbendpoint: dbId,
    }; //TODO: to implement
    localStorage.setItem("currentdb", JSON.stringify(currentDb));
    if (dbType == "project") {
      router.push("/pmgmt");
    }
  };
  return (
    <>
      <div className={styles.wrapper}>
        <Head>
          <title>Personal Database</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className={styles.title}>Select Database</h1>

        {isLoading ? (
          <div>
            <p>Loading</p>
          </div>
        ) : (
          <div className={styles.grid}>
            {databases.map((database, key) => (
              <Card
                className={styles.projectCard}
                key={key}
                onClick={() =>
                  NavigatePages(
                    database.description,
                    database.type,
                    database.name,
                    database.id
                  )
                }
              >
                <h2>{database.name}</h2>
                <p>{database.description}</p>
              </Card>
            ))}
          </div>
        )}
      </div>
      <Snackbar
        open={snackOpen}
        autoHideDuration={3000}
        onClose={() => setSnackOpen(false)}
        message="Created New Database Successfully 🎉️"
        action={
          <>
            <IconButton
              size="small"
              aria-label="close"
              color="inherit"
              onClick={() => setSnackOpen(false)}
            >
              <Close />
            </IconButton>
          </>
        }
      />
      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="form-dialog-title"
      >
        <DialogTitle id="form-dialog-title">Create New Database</DialogTitle>
        <DialogContent>
          <DialogContentText>
            Enter details to add new Database.
          </DialogContentText>
          <TextField
            autoFocus
            margin="dense"
            id="name"
            onChange={(e) => setName(e.target.value)}
            label="Name"
            type="text"
            fullWidth
          />
          <TextField
            autoFocus
            margin="dense"
            id="desc"
            onChange={(e) => setDesc(e.target.value)}
            label="Description"
            type="text"
            fullWidth
          />
          <Select
            native
            value={type}
            onChange={handleTypeChange}
            inputProps={{
              name: "type",
              id: "select-type",
            }}
          >
            <option value={"project"}>Project</option>
            <option value={"table"}>Table (comming soon)</option>
            <option value={"list"}>Lists (comming soon)</option>
          </Select>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClose} color="primary">
            Cancel
          </Button>
          <Button onClick={AddProject} color="primary">
            Create
          </Button>
        </DialogActions>
      </Dialog>
      <Fab
        color="primary"
        aria-label="add"
        className={styles.fab}
        onClick={() => setOpen(true)}
      >
        <AddRounded />
      </Fab>
    </>
  );
}
